name: Scrape & Deploy

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install supabase
          pip install python-dotenv

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run scraper
        run: python scraper/scraper.py

      - name: Deduplicate results
        run: python scraper/deduplicate.py

      - name: Upload to Supabase
        run: python scraper/upload_to_supabase.py

      - name: Generate sitemap
        run: npm run sitemap

      - name: Trigger Vercel Rebuild (No Hook)
        run: |
          curl -X POST https://api.vercel.com/v1/projects/hmtenn/deployments \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"name":"hmtenn","gitSource":{"type":"github","repoId":"PropertyNoticeHub/HMTENN"}}'
