name: Run Handyman Scraper

on:
  schedule:
    - cron: "0 2 * * *" # Run every day at 2AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install -r scraper/requirements.txt
          pip install python-dotenv

      - name: Run scraper
        run: python scraper/scraper.py

      - name: Deduplicate results
        run: python scraper/deduplicate.py

      - name: Upload to Supabase
        run: python scraper/upload_to_supabase.py

      - name: Regenerate sitemap
        run: npm run sitemap

      - name: Trigger Vercel Deploy (API)
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_xxxxxxx" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
